# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgh < Formula
  desc "Terminal UI for browsing GitHub Actions workflow runs and job logs"
  homepage "https://github.com/philipparndt/tgh"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philipparndt/tgh/releases/download/v0.3.0/tgh_darwin_x86_64.tar.gz"
      sha256 "332b632bd6710c6d1e89aec655e83dfbc5d1f91a22c85d0b8c2ef15a58c4c6ec"

      define_method(:install) do
        bin.install "tgh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philipparndt/tgh/releases/download/v0.3.0/tgh_darwin_arm64.tar.gz"
      sha256 "3632742ebfef6931d85d89add9a808f719ad75c53a2efe7f1dc71c5ac1b84054"

      define_method(:install) do
        bin.install "tgh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/tgh/releases/download/v0.3.0/tgh_linux_x86_64.tar.gz"
      sha256 "726237a5c1b225d101a163dce7b8ad7c9bd7cc09912e848e1e707a5d6ed3585d"
      define_method(:install) do
        bin.install "tgh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/tgh/releases/download/v0.3.0/tgh_linux_arm64.tar.gz"
      sha256 "4a4cca454cf14b0bc2932be1ad1b2b53b79137469e33a43556a41b2e7426a93c"
      define_method(:install) do
        bin.install "tgh"
      end
    end
  end
end
