# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgh < Formula
  desc "Terminal UI for browsing GitHub Actions workflow runs and job logs"
  homepage "https://github.com/philipparndt/tgh"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philipparndt/tgh/releases/download/v0.1.1/tgh_darwin_x86_64.tar.gz"
      sha256 "4a02361ed202136e880e3b6a95323ef020f40bbca0658225da72d39fae615ca4"

      define_method(:install) do
        bin.install "tgh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philipparndt/tgh/releases/download/v0.1.1/tgh_darwin_arm64.tar.gz"
      sha256 "e9c4a101741debae2ab8260218480718b50ba5c5d60294b60a73b326a7708380"

      define_method(:install) do
        bin.install "tgh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/tgh/releases/download/v0.1.1/tgh_linux_x86_64.tar.gz"
      sha256 "bb953fa8e4ec3197e2d2e9268cc73a347aba1141e39ad81281c5ad22d627a4c2"
      define_method(:install) do
        bin.install "tgh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/tgh/releases/download/v0.1.1/tgh_linux_arm64.tar.gz"
      sha256 "d3c7074e1d4ccacf28ac5f3de59722305564e6915a131e26ace163950d0d1376"
      define_method(:install) do
        bin.install "tgh"
      end
    end
  end
end
